### ISSUE TITLE
Realign subject form inputs

### ISSUE THREAD

**Issue by AJLC-TAY** [AJLC-TAY/GEMIS-IT-PROJECT#1]
# Design Team
Rearrange the input fields of the subject form. If user selects a program type, the program choices are not showing. I forgot to include its code when transferring the files to the directory. Just rearrange the inputs. 
   - File: subjectform.php
   
![image](https://user-images.githubusercontent.com/72988090/131668111-9f33b229-9d9d-4c26-85cd-b561db3bb2e2.png)

**Comment by Caryl2192339** [comment]
Realigned subject form inputs:

![image](https://user-images.githubusercontent.com/47551462/132361280-d31a1952-0847-46ae-a439-ae5dd062b7b0.png)
![image](https://user-images.githubusercontent.com/47551462/132361368-0031759a-345b-4d82-9d57-13ddb3b7b407.png)
