### ISSUE TITLE
Update foreign key constraint

### ISSUE THREAD

**Issue by AJLC-TAY** [AJLC-TAY/GEMIS-IT-PROJECT#2]
Turn on the delete cascade of requisite in the sharedsubject table. Archiving subjects is not allowed when the constraint is set to on delete not allowed.

**Comment by marielpenaflor** [comment]
Run this query to change constraint. Updated SQL file in Database drive folder:

ALTER TABLE `gemis`.`requisite` 
DROP FOREIGN KEY `fk_requisite_subject2`;
ALTER TABLE `gemis`.`requisite` 
ADD CONSTRAINT `fk_requisite_subject2`
  FOREIGN KEY (`req_sub_code`)
  REFERENCES `gemis`.`subject` (`sub_code`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
