### ISSUE TITLE
Add distance between cards at their y-axis

### ISSUE THREAD

**Issue by AJLC-TAY** [AJLC-TAY/GEMIS-IT-PROJECT#7]
![Screenshot from 2021-09-13 23-10-27](https://user-images.githubusercontent.com/72988090/133109648-c60b4890-0fad-4e23-b01e-8aee87dc0fbe.png)

**Comment by Caryl2192339** [comment]
![image](https://user-images.githubusercontent.com/47551462/133642693-1e54343d-1814-4223-92dd-bd5ef7e88656.png)
