### ISSUE TITLE
Increase varchar lenght for home_no attribute under address table

### ISSUE THREAD

**Issue by AJLC-TAY** [AJLC-TAY/GEMIS-IT-PROJECT#8]

**Comment by marielpenaflor** [comment]
ALTER TABLE `gemis`.`address` 
CHANGE COLUMN `home_no` `home_no` VARCHAR(45) NULL DEFAULT NULL ;
ALTER TABLE `gemis`.`archived_address` 
CHANGE COLUMN `home_no` `home_no` VARCHAR(45) NULL DEFAULT NULL ;
